// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package util

import (
	"github.com/cloudfoundry-community/go-cfclient"
	"github.com/mike-carey/cfquery/logger"
	"github.com/pkg/errors"
)

func OrgGroupBy(items []cfclient.Org, getKey func(cfclient.Org) (string, error)) (map[string][]cfclient.Org, error) {
	pool := make(map[string][]cfclient.Org, 0)

	for _, item := range items {
		key, err := getKey(item)
		if err != nil {
			logger.Errorf("Could not get key from item: %v", item)
			return nil, errors.Wrap(err, "Could not get key for item")
		}

		if _, ok := pool[key]; !ok {
			pool[key] = make([]cfclient.Org, 0)
		}

		logger.Infof("Adding item to %s entry", key)
		pool[key] = append(pool[key], item)
	}

	logger.Infof("Returning %d groups in slice", len(pool))
	return pool, nil
}

func OrgGroupMapBy(items map[string]cfclient.Org, getKey func(cfclient.Org) (string, error)) (map[string]map[string]cfclient.Org, error) {
	pool := make(map[string]map[string]cfclient.Org, 0)

	for origKey, item := range items {
		key, err := getKey(item)
		if err != nil {
			logger.Errorf("Could not get key from item: %v", item)
			return nil, errors.Wrap(err, "Could not get key for item")
		}

		if _, ok := pool[key]; !ok {
			pool[key] = make(map[string]cfclient.Org, 0)
		}

		logger.Infof("Adding %s item to %s entry", origKey, key)
		pool[key][origKey] = item
	}

	logger.Infof("Returning %d groups in map", len(pool))
	return pool, nil
}
