// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query_test

import (
	. "github.com/mike-carey/cfquery/query"
	. "github.com/onsi/gomega"
	. "github.com/onsi/ginkgo"
	"fmt"
	"io"
	"reflect"

	"github.com/cloudfoundry-community/go-cfclient"
	"github.com/mike-carey/cfquery/cf/fakes"
)

func getSpaceServiceName() string {
	return fmt.Sprintf("%v", reflect.TypeOf(SpaceService{}))
}

func getSpaceName() string {
	return fmt.Sprintf("%v", reflect.TypeOf(cfclient.Space{}))
}

func newSpace(guid string) cfclient.Space {
	return cfclient.Space{
		Guid: guid,
	}
}

func SpaceShouldImplementService(service Service) {
	io.WriteString(GinkgoWriter, fmt.Sprintf("If this did not compile, it indicates that %v does not implement Service", reflect.TypeOf(&cfclient.Space{})))
}

var _ = Describe(getSpaceServiceName()+"Base", func() {

	var (
		fakeClient *fakes.FakeCFClient
		service    *SpaceService
	)

	BeforeEach(func() {
		fakeClient = new(fakes.FakeCFClient)
		service = NewSpaceService(fakeClient)
	})

	It("Should Implement Service", func() {
		SpaceShouldImplementService(service)
	})

	It("Should Get All "+getSpaceName()+"s", func() {
		By("Calling the CFClient")
		expect := Spaces{
			newSpace("one"),
			newSpace("two"),
			newSpace("three"),
		}

		fakeClient.ListSpacesReturns(expect, nil)

		actual, err := service.GetAllSpaces()

		Expect(err).To(BeNil())
		Expect(actual).Should(ConsistOf(expect))

		Expect(fakeClient.ListSpacesCallCount()).To(Equal(1))

		By("Using the storage")

		actual2, err2 := service.GetAllSpaces()

		Expect(err2).To(BeNil())
		Expect(actual2).Should(ConsistOf(expect))

		// It should still equal 1
		Expect(fakeClient.ListSpacesCallCount()).To(Equal(1))
	})

})
