// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query_test

import (
	. "github.com/mike-carey/cfquery/query"
	. "github.com/onsi/gomega"
	. "github.com/onsi/ginkgo"
	"fmt"
	"io"
	"reflect"

	"github.com/cloudfoundry-community/go-cfclient"
	"github.com/mike-carey/cfquery/cf/fakes"
)

func getOrgServiceName() string {
	return fmt.Sprintf("%v", reflect.TypeOf(OrgService{}))
}

func getOrgName() string {
	return fmt.Sprintf("%v", reflect.TypeOf(cfclient.Org{}))
}

func newOrg(guid string) cfclient.Org {
	return cfclient.Org{
		Guid: guid,
	}
}

func OrgShouldImplementService(service Service) {
	io.WriteString(GinkgoWriter, fmt.Sprintf("If this did not compile, it indicates that %v does not implement Service", reflect.TypeOf(&cfclient.Org{})))
}

var _ = Describe(getOrgServiceName()+"Base", func() {

	var (
		fakeClient *fakes.FakeCFClient
		service    *OrgService
	)

	BeforeEach(func() {
		fakeClient = new(fakes.FakeCFClient)
		service = NewOrgService(fakeClient)
	})

	It("Should Implement Service", func() {
		OrgShouldImplementService(service)
	})

	It("Should Get All "+getOrgName()+"s", func() {
		By("Calling the CFClient")
		expect := Orgs{
			newOrg("one"),
			newOrg("two"),
			newOrg("three"),
		}

		fakeClient.ListOrgsReturns(expect, nil)

		actual, err := service.GetAllOrgs()

		Expect(err).To(BeNil())
		Expect(actual).Should(ConsistOf(expect))

		Expect(fakeClient.ListOrgsCallCount()).To(Equal(1))

		By("Using the storage")

		actual2, err2 := service.GetAllOrgs()

		Expect(err2).To(BeNil())
		Expect(actual2).Should(ConsistOf(expect))

		// It should still equal 1
		Expect(fakeClient.ListOrgsCallCount()).To(Equal(1))
	})

})
