// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import "github.com/cloudfoundry-community/go-cfclient"

type Apps []cfclient.App
type AppMap map[string]cfclient.App
type AppGroup map[string]Apps
type MappedAppMap map[string]AppMap
type MappedAppGroup map[string]AppGroup

// func (i *Apps) ToJson() {
// 	enc := json.NewEncoder(os.Stdin)
// 	enc.SetIndent("", "    ")
// 	if err := enc.Encode(&a); err != nil {
// 		panic(err)
// 	}
