// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query_test

import (
	. "github.com/mike-carey/cfquery/query"
	. "github.com/onsi/gomega"
	. "github.com/onsi/ginkgo"
	"fmt"
	"io"
	"reflect"

	"github.com/cloudfoundry-community/go-cfclient"
	"github.com/mike-carey/cfquery/cf/fakes"
)

func getStackServiceName() string {
	return fmt.Sprintf("%v", reflect.TypeOf(StackService{}))
}

func getStackName() string {
	return fmt.Sprintf("%v", reflect.TypeOf(cfclient.Stack{}))
}

func newStack(guid string) cfclient.Stack {
	return cfclient.Stack{
		Guid: guid,
	}
}

func StackShouldImplementService(service Service) {
	io.WriteString(GinkgoWriter, fmt.Sprintf("If this did not compile, it indicates that %v does not implement Service", reflect.TypeOf(&cfclient.Stack{})))
}

var _ = Describe(getStackServiceName()+"Base", func() {

	var (
		fakeClient *fakes.FakeCFClient
		service    *StackService
	)

	BeforeEach(func() {
		fakeClient = new(fakes.FakeCFClient)
		service = NewStackService(fakeClient)
	})

	It("Should Implement Service", func() {
		StackShouldImplementService(service)
	})

	It("Should Get All "+getStackName()+"s", func() {
		By("Calling the CFClient")
		expect := Stacks{
			newStack("one"),
			newStack("two"),
			newStack("three"),
		}

		fakeClient.ListStacksReturns(expect, nil)

		actual, err := service.GetAllStacks()

		Expect(err).To(BeNil())
		Expect(actual).Should(ConsistOf(expect))

		Expect(fakeClient.ListStacksCallCount()).To(Equal(1))

		By("Using the storage")

		actual2, err2 := service.GetAllStacks()

		Expect(err2).To(BeNil())
		Expect(actual2).Should(ConsistOf(expect))

		// It should still equal 1
		Expect(fakeClient.ListStacksCallCount()).To(Equal(1))
	})

})
