// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query_test

import (
	. "github.com/mike-carey/cfquery/query"
	. "github.com/onsi/gomega"
	. "github.com/onsi/ginkgo"
	"fmt"
	"io"
	"reflect"

	"github.com/cloudfoundry-community/go-cfclient"
	"github.com/mike-carey/cfquery/cf/fakes"
)

func getAppServiceName() string {
	return fmt.Sprintf("%v", reflect.TypeOf(AppService{}))
}

func getAppName() string {
	return fmt.Sprintf("%v", reflect.TypeOf(cfclient.App{}))
}

func newApp(guid string) cfclient.App {
	return cfclient.App{
		Guid: guid,
	}
}

func AppShouldImplementService(service Service) {
	io.WriteString(GinkgoWriter, fmt.Sprintf("If this did not compile, it indicates that %v does not implement Service", reflect.TypeOf(&cfclient.App{})))
}

var _ = Describe(getAppServiceName()+"Base", func() {

	var (
		fakeClient *fakes.FakeCFClient
		service    *AppService
	)

	BeforeEach(func() {
		fakeClient = new(fakes.FakeCFClient)
		service = NewAppService(fakeClient)
	})

	It("Should Implement Service", func() {
		AppShouldImplementService(service)
	})

	It("Should Get All "+getAppName()+"s", func() {
		By("Calling the CFClient")
		expect := Apps{
			newApp("one"),
			newApp("two"),
			newApp("three"),
		}

		fakeClient.ListAppsReturns(expect, nil)

		actual, err := service.GetAllApps()

		Expect(err).To(BeNil())
		Expect(actual).Should(ConsistOf(expect))

		Expect(fakeClient.ListAppsCallCount()).To(Equal(1))

		By("Using the storage")

		actual2, err2 := service.GetAllApps()

		Expect(err2).To(BeNil())
		Expect(actual2).Should(ConsistOf(expect))

		// It should still equal 1
		Expect(fakeClient.ListAppsCallCount()).To(Equal(1))
	})

})
