// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import (
	"reflect"
	"sync"

	"github.com/cloudfoundry-community/go-cfclient"
	"github.com/mike-carey/cfquery/cf"
	"github.com/mike-carey/cfquery/logger"
)

type ServiceBindingService struct {
	Client  cf.CFClient
	storage map[string]cfclient.ServiceBinding
	filled  bool
	mutex   *sync.Mutex
}

func NewServiceBindingService(client cf.CFClient) *ServiceBindingService {
	return &ServiceBindingService{
		Client:  client,
		storage: make(map[string]cfclient.ServiceBinding, 0),
		filled:  false,
		mutex:   &sync.Mutex{},
	}
}

func (s *ServiceBindingService) lock() {
	s.mutex.Lock()
	logger.Infof("Locked %v", reflect.TypeOf(s))
}

func (s *ServiceBindingService) unlock() {
	s.mutex.Unlock()
	logger.Infof("Unlocked %v", reflect.TypeOf(s))
}

func (s *ServiceBindingService) GetStorage() (map[string]cfclient.ServiceBinding, error) {
	_, err := s.GetAll()
	if err != nil {
		return nil, err
	}

	return s.storage, nil
}

func (s *ServiceBindingService) GetByGuid(guid string) (*cfclient.ServiceBinding, error) {
	s.lock()

	defer s.unlock()

	if s.filled {
		if val, ok := s.storage[guid]; ok {
			return &val, nil
		}
	}

	logger.Infof("Did not find %s in storage", guid)
	item, err := s.Client.GetServiceBindingByGuid(guid)
	if err != nil {
		return nil, err
	}

	// Save off in storage
	s.storage[guid] = item

	return &item, nil
}

func (s *ServiceBindingService) GetManyByGuid(guids ...string) (map[string]cfclient.ServiceBinding, error) {
	pool := make(map[string]cfclient.ServiceBinding, len(guids))

	type Result struct {
		Guid   string
		Object *cfclient.ServiceBinding
		Error  error
	}

	resCh := make(chan Result, len(guids))

	for _, guid := range guids {
		go func(guid string) {
			obj, err := s.GetByGuid(guid)
			res := Result{
				Guid:   guid,
				Error:  err,
				Object: obj,
			}

			resCh <- res
		}(guid)
	}

	errs := make([]error, 0)

	for _, _ = range guids {
		select {
		case res := <-resCh:
			if res.Error != nil {
				errs = append(errs, res.Error)
			}

			pool[res.Guid] = *res.Object
		}
	}

	if len(errs) > 0 {
		return nil, StackErrors(errs)
	}

	return pool, nil
}

func (s *ServiceBindingService) GetAll() ([]cfclient.ServiceBinding, error) {
	s.lock()

	if s.filled {
		logger.Infof("Reusing storage")
		siSlice := make([]cfclient.ServiceBinding, 0, len(s.storage))
		for _, si := range s.storage {
			siSlice = append(siSlice, si)
		}

		s.unlock()

		return siSlice, nil
	}

	logger.Infof("Calling out to CFClient")
	sis, err := s.Client.ListServiceBindings()
	if err != nil {
		return nil, err
	}

	go func(s *ServiceBindingService, sis []cfclient.ServiceBinding) {
		logger.Infof("Storing contents to storage")
		for _, si := range sis {
			s.storage[si.Guid] = si
		}

		logger.Infof("Done storing contents to storage")
		s.filled = true

		s.unlock()
	}(s, sis)

	logger.Infof("Returning list while populating happens")
	return sis, nil
}

func (i *Inquistor) GetServiceBindingService() *ServiceBindingService {
	if i.ServiceBindingService == nil {
		i.ServiceBindingService = NewServiceBindingService(i.CFClient)
	}

	return i.ServiceBindingService
}
