// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package query

import (
	"fmt"
	"reflect"
	"strings"
	"sync"

	"github.com/cloudfoundry-community/go-cfclient"
	"github.com/mike-carey/cfquery/cf"
	"github.com/mike-carey/cfquery/logger"
)

type SpaceService struct {
	Client      cf.CFClient
	storage     map[string]cfclient.Space
	filled      bool
	mutex       *sync.Mutex
	serviceName string
	key         string
}

func NewSpaceService(client cf.CFClient) *SpaceService {
	return &SpaceService{
		Client:  client,
		storage: make(map[string]cfclient.Space, 0),
		filled:  false,
		mutex:   &sync.Mutex{},
	}
}

func (s *SpaceService) ServiceName() string {
	return fmt.Sprintf("%v", reflect.TypeOf(s))
}

func (s *SpaceService) Key() string {
	return strings.Split(s.ServiceName(), "Service")[0]
}

func (s *SpaceService) lock() {
	s.mutex.Lock()
	logger.Infof("Locked %v", reflect.TypeOf(s))
}

func (s *SpaceService) unlock() {
	s.mutex.Unlock()
	logger.Infof("Unlocked %v", reflect.TypeOf(s))
}

func (s *SpaceService) GetStorage() (map[string]cfclient.Space, error) {
	_, err := s.GetAll()
	if err != nil {
		return nil, err
	}

	return s.storage, nil
}

func (s *SpaceService) GetByGuid(guid string) (*cfclient.Space, error) {
	s.lock()

	defer s.unlock()

	if s.filled {
		if val, ok := s.storage[guid]; ok {
			return &val, nil
		}
	}

	logger.Infof("Did not find %s in storage", guid)
	item, err := s.Client.GetSpaceByGuid(guid)
	if err != nil {
		return nil, err
	}

	// Save off in storage
	s.storage[guid] = item

	return &item, nil
}

func (s *SpaceService) GetManyByGuid(guids ...string) (map[string]cfclient.Space, error) {
	pool := make(map[string]cfclient.Space, len(guids))

	type Result struct {
		Guid   string
		Object *cfclient.Space
		Error  error
	}

	resCh := make(chan Result, len(guids))

	for _, guid := range guids {
		go func(guid string) {
			obj, err := s.GetByGuid(guid)
			res := Result{
				Guid:   guid,
				Error:  err,
				Object: obj,
			}

			resCh <- res
		}(guid)
	}

	errs := make([]error, 0)

	for _, _ = range guids {
		select {
		case res := <-resCh:
			if res.Error != nil {
				errs = append(errs, res.Error)
			}

			pool[res.Guid] = *res.Object
		}
	}

	if len(errs) > 0 {
		return nil, StackErrors(errs)
	}

	return pool, nil
}

func (s *SpaceService) GetAll() ([]cfclient.Space, error) {
	s.lock()

	if s.filled {
		logger.Infof("Reusing storage")
		siSlice := make([]cfclient.Space, 0, len(s.storage))
		for _, si := range s.storage {
			siSlice = append(siSlice, si)
		}

		s.unlock()

		return siSlice, nil
	}

	logger.Infof("Calling out to CFClient")
	sis, err := s.Client.ListSpaces()
	if err != nil {
		return nil, err
	}

	go func(s *SpaceService, sis []cfclient.Space) {
		logger.Infof("Storing contents to storage")
		for _, si := range sis {
			s.storage[si.Guid] = si
		}

		logger.Infof("Done storing contents to storage")
		s.filled = true

		s.unlock()
	}(s, sis)

	logger.Infof("Returning list while populating happens")
	return sis, nil
}

func (i *Inquistor) NewSpaceService() *SpaceService {
	return NewSpaceService(i.CFClient)
}

func (i *Inquistor) GetSpaceService() *SpaceService {
	class := &SpaceService{}
	service := i.GetService(class.key)

	return service.(*SpaceService)
}
