// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package generics

type Foos []Foo
type FooMap map[string]Foo
type FooGroup map[string]Foos
type MappedFooMap map[string]FooMap
type MappedFooGroup map[string]FooGroup
