// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package generics

import (
	"github.com/mike-carey/cfquery/logger"
	"github.com/pkg/errors"
)

func FooFilterBy(items []Foo, check func(Foo) (bool, error)) ([]Foo, error) {
	pool := make([]Foo, 0)

	for _, item := range items {
		ok, err := check(item)
		if err != nil {
			logger.Errorf("Could not check filter on: %v", item)
			return nil, errors.Wrap(err, "Could not check filter for item")
		}

		if ok {
			logger.Infof("Adding item to entry")
			pool = append(pool, item)
		}
	}

	logger.Infof("Returning filtered slice of size %d", len(pool))
	return pool, nil
}
